version: "3.8"
services:
  vpn:
    build:
      context: .
      dockerfile: ./vpn/Dockerfile
    container_name: vpn
    ports:
      - 8080:8080


  store:
    build:
      context: .
      dockerfile: ./store/Dockerfile
    container_name: store
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8082:8082

  blocknot:
    build:
      context: .
      dockerfile: ./blocknot/Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres